name: carousel
description: A Flutter Carousel.
version: 0.1.0
author: Gabriel Valério <gbrvalerio@gmail.com>
homepage: https://github.com/gbrvalerio/carousel

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.58.0 <3.0.0"

dev_dependencies:
  test: ^0.12.0
